books/urls.py
from django.urls import path
from books import views

app_name = 'books'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('authors/', views.AuthorListView.as_view(), name='list_authors'),
    path('authors/add/', views.AuthorCreateView.as_view(), name='add_author'),
    path('authors/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),
    path('authors/<int:pk>/books/edit/', views.AuthorBooksEditView.as_view(), name='author_book_edit')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='books'))
]

books/models.py
from django.db import models
from django.urls import reverse


class Author(models.Model):
    name = models.CharField(null=False, blank=False, max_length=255)
    
    def get_absolute_url(self):
        return reverse('books:author_detail', kwargs={'pk': self.pk})
    
    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(null=False, blank=False, max_length=255)
    author = models.ForeignKey('Author', null=False, blank=False, on_delete=models.CASCADE, related_name='book_author')
    
    def __str__(self):
        return self.title

books/forms.py
from django.forms.models import inlineformset_factory

from .models import Author, Book

AuthorBooksFormset = inlineformset_factory(Author, Book, fields=('title',))

books/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, ListView, CreateView, DetailView, FormView)
from books.models import Author, Book
from .forms import AuthorBooksFormset
from django.contrib import messages
from django.views.generic.detail import SingleObjectMixin
from django.http import HttpResponseRedirect
from django.urls import reverse


class HomeView(TemplateView):
    template_name = 'home.html'
    

class AuthorListView(ListView):
    template_name = 'author_list.html'
    model = Author


class AuthorDetailView(DetailView):
    model = Author
    template_name = 'author_detail.html'

    
class AuthorCreateView(CreateView):
    template_name = 'author_create.html'
    model = Author
    fields = ['name',]
    
    def form_valid(self, form):
        messages.add_message(
            self.request,
            messages.SUCCESS,
            'The author has been added'
        )
        
        return super().form_valid(form)


class AuthorBooksEditView(SingleObjectMixin, FormView):

    model = Author
    template_name = 'author_books_edit.html'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Author.objects.all())
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Author.objects.all())
        return super().post(request, *args, **kwargs)

    def get_form(self, form_class=None):
        return AuthorBooksFormset(**self.get_form_kwargs(), instance=self.object)

    def form_valid(self, form):
        form.save()

        messages.add_message(
            self.request,
            messages.SUCCESS,
            'Changes were saved.'
        )

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('books:author_detail', kwargs={'pk': self.object.pk})
    

books/templates/author_books_edit.html
{% extends 'base.html' %}

{% block title %}Editing books for {{ author.name }}{% endblock %}

{% block content %}
  <form action="" method="post" enctype="multipart/form-data">

    {% for hidden_field in form.hidden_fields %}
      {{ hidden_field.errors }}
      {{ hidden_field }}
    {% endfor %}

    {% csrf_token %}

    {{ form.management_form }}
    {{ form.non_form_errors }}

    <h3>Update Collection</h3>
    {% for book_form in form.forms %}
      <hr>
      <h5>
        {% if book_form.instance.id %}
          Book: {{ book_form.instance.title|title }}
        {% else %}
          {% if form.forms|length > 1 %}
            Add another book
          {% else %}
            Add a book
          {% endif %}
        {% endif %}
      </h5>
      {% for hidden_field in book_form.hidden_fields %}
        {{ hidden_field.errors }}
      {% endfor %}
      <table>
        {{ book_form.as_table }}
      </table>
    {% endfor %}
    <hr>
    <p>
      <button type="submit" value="Update collection" class="btn btn-primary w-100 mb-3">Update Collection</button>
      <a href="{{ author.get_absolute_url  }}" role="button" class="btn btn-secondary w-100">Cancel</a>
    </p>
  </form>

{% endblock content %}

books/templates/author_create.html
{% extends 'base.html' %}

{% block title %}New Author{% endblock %}

{% block content %}

      <form action="" method="post">
        {% for hidden_field in form.hidden_fields %}
          {{ hidden_field.errors }}
          {{ hidden_field }}
        {% endfor %}

        {% csrf_token %}

        {{ form.non_form_errors }}

        {% for field in form %}
          {{ field.errors }}
          {{ field.label_tag }} {{ field }}
        {% endfor %}

        <p class="pt-2">
            <button type="submit" class="btn btn-primary w-100 mb-2">Add Author</button>
            <a href="{% url 'books:home' %}" role="button" class="btn btn-secondary w-100">Cancel</a>
        </p>
      </form>

{% endblock content %}

books/templates/author_detail.html
{% extends 'base.html' %}

{% block title %}{{ author.name }}{% endblock %}

{% block content %}

    {% if messages %}
      <ul class="messages">
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
      </ul>
    {% endif %}

    <h3>Authors Book Details</h3>
    <div class="d-flex d-flex-inline"><span class="pe-2">Authors name:</span> <h5>{{ author.name|title }}</h5></div>
    <hr>
        {% for book in author.book_author.all %}
        <div class="small">Book ID: {{ book.id }}</div>
        <div>Title: {{ book.title }}</div>
        <hr>
        {% endfor %}
    <p>
        <a href="{% url 'books:author_book_edit' pk=author.pk %}" role="button" class="btn btn-primary w-100 mb-2">Edit Authors Books</a>
        <a href="{% url 'books:list_authors' %}" role="button" class="btn btn-secondary w-100">All Collection</a>
    </p>


{% endblock content %}

books/templates/author_list.html
{% extends 'base.html'  %}
{% block title  %}Authors{% endblock  %}

{% block content  %}

<h3>Author Lists</h3>
{% if author_list  %}

    {% for author in author_list  %}
        <li class="list-group-item">
            <a class="text-reset" href="{{ author.get_absolute_url }}">{{author.name}}</a>
        </li>
    {% endfor %}

    {% else %}
    <p>There is no author to dispaly</p>

{% endif %}
<p class="pt-2">
    <a href="{% url 'books:home'  %}" role="button" class="btn btn-secondary w-100 mb-2">Cancel</a>
</p>
{% endblock content  %}

books/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js"></script>

    <title>{% block title  %}Homepage{% endblock  %}</title>
</head>
<body>
    <main>
        <div class="container-fluid">
            <div class="d-flex align-items-center py-5">
                <div class="col-12 col-md-6 col-lg-4 mx-auto">
                    {% block content  %}

                    {% endblock content  %}
                </div>
            </div>
        </div>
    </main>
</body>
</html>

books/templates/home.html
{% extends 'base.html'  %}
{% block title  %}Homepage{% endblock  %}

{% block content  %}

<h3>BookStore Collections</h3>
<a href="{% url 'books:list_authors'  %}" role="button" class="btn btn-primary w-100 mb-2">All Authors</a>
<a href="{% url 'books:add_author' %}" role="button" class="btn btn-secondary w-100">Add an Author</a>
{% endblock content  %}